<a href="https://colab.research.google.com/github/gusrhs11/CS231n/blob/main/Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS231n Python Tutorial

Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes

Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting

Matplotlib: Plotting, Subplots, Images

IPython: Creating notebooks, Typical workflows

In [71]:
def quicksort(arr):
  if len(arr) <= 1:
    return arr
  pivot = arr[len(arr)//2]
  left = [x for x in arr if x < pivot]
  middle = [x for x in arr if x == pivot]
  right = [x for x in arr if x > pivot]

  return quicksort(left) + middle + quicksort(right)

print(quicksort([4, 6, 4, 5, 1, 9, 3, 8]))


[1, 3, 4, 4, 5, 6, 8, 9]


Basic data types




In [4]:
#numbers
x = 3
print(x, type(x))

3 <class 'int'>


In [5]:
#booleans
t,f = True , False
print(type(t))

<class 'bool'>


In [6]:
#Strings
hello = 'hello'
world = 'wd'
hw = hello + ' ' + world
print(hw)

hello wd


In [10]:
hw12 = '{} {} {}'.format(hello, world, 12) # string formatting ---> simillar to C formatting
print(hw)
s = 'hello world'
print(s.capitalize()) # first letter to upper case
print(s.upper())      # every letters to upper case
print(s.rjust(7))     # 오른쪽 맞춤
print(s.center(7))    # 가운데 맞춤
print(s.replace('l', '(ell)')) # replace all 'l' to '(ell)'
print('  wor ld'.strip())      #앞 뒤 공백 제거

hello wd
Hello world
HELLO WORLD
hello world
hello world
he(ell)(ell)o wor(ell)d
wor ld


Containers

In [14]:
#List
xs = [3, 1, 2]
print(xs[-1]) # negative index starts from the end
xs[2] = 'foo' # List can contain differnet types
print(xs)
xs.append('bar') # add
print(xs)
x = xs.pop() # pop last element
print(xs)

2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
[3, 1, 'foo']


In [16]:
#slicing
nums = list(range(5))
print(nums)
print(nums[2:4])    #2번 인덱스 시작 (4-2)개 slicing
print(nums[2:])     #2 to end
print(nums[:2])     #start 시작 2개 slicing
print(nums[:])      #전체
print(nums[:-1])    #뒤에서 하나 뺌
nums[2:4] = [8,9]   #assign도 가능
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [18]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
  print(animal)
for idx, animal in enumerate(animals):      #if you want access to the index of each element
  print('#{}: {}'.format(idx + 1, animal))

cat
dog
monkey
#1: cat
#2: dog
#3: monkey


In [27]:
#List comprehensions
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
  squares.append(x**2)
print(squares)
squares = [x**2 for x in nums]
print(squares)
even_squares = [x**2 for x in nums if x%2 == 0]
print(even_squares)
nums = [[0 for j in range(6)] for i in range(5)]    #2차원 배열 초기화
print(nums)

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[0, 4, 16]
[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]


In [33]:
#Dictionaries
d = {'cat' : 'cute', 'dog' : 'furry'}
print(d['cat'])
print('cat' in d)
d['fish'] = 'wet'
print(d['fish'])
#print(d['monk']) - keyerror
print(d.get('monkey', 'N/A')) # default; N/A
print(d.get('fish', 'N/A'))
del d['fish']
print(d.get('fish', 'N/A'))

cute
True
wet
N/A
wet
N/A


In [35]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
  print('A {} has {} legs'.format(animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [36]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0} # 'x:'를 앞에 붙이면 dictionary로 앞이 key, 뒤가 value
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


In [40]:
#Sets
animals = {'cat', 'dog'}
print('cat' in animals)       # x in set -> 조건문
print('fish' in animals)
animals.add('fish')
print('fish' in animals)
print(len(animals))
animals.add('cat')
print(len(animals))
animals.remove('cat')
print(len(animals))

True
False
True
3
3
2


In [41]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
  print('#{}: {}'.format(idx + 1, animal))

#1: fish
#2: dog
#3: cat


In [43]:
from math import sqrt
print({sqrt(x) for x in range(30)})
print({int(sqrt(x)) for x in range(30)})

{0.0, 1.0, 2.0, 1.7320508075688772, 1.4142135623730951, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0, 3.1622776601683795, 3.3166247903554, 3.4641016151377544, 4.0, 5.0, 4.47213595499958, 4.795831523312719, 4.898979485566356, 5.0990195135927845, 5.196152422706632, 5.291502622129181, 3.7416573867739413, 3.872983346207417, 4.123105625617661, 4.242640687119285, 4.358898943540674, 4.58257569495584, 4.69041575982343, 5.385164807134504, 3.605551275463989}
{0, 1, 2, 3, 4, 5}


In [47]:
#Tuples -- tuple is almost same as list but the most important diffence is that tuples can be used as keys in dic
#           and elements of sets, while lists cannot
d = {(x, x + 1) : x for x in range(10)}
t = (5, 6)
l = [5, 6]
print(type(t), type(d), type(l))
print(d)
print(d[t])
print(d[(1, 2)])
#print(d[l])

<class 'tuple'> <class 'dict'> <class 'list'>
{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
5
1


In [48]:
#Functions
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [49]:
def hello(name, loud=False):            #default input
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
          print('HELLO, {}'.format(self.name.upper()))
        else:
          print('Hello, {}!'.format(self.name))

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

#Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [50]:
import numpy as np

In [51]:
a = np.array([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [54]:
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


In [58]:
a = np.zeros((2,2))
b = np.ones((1,2))
c = np.full((2,2), 7)
print(a)
print(b)
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]


In [66]:
d = np.eye(2)
e = np.eye(3)
print(d)
print(e)
f = np.random.random((2,2))
print(f)
g = np.random.random(5)
print(g)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.58418451 0.04074162]
 [0.50073611 0.84967582]]
[0.54151067 0.97450501 0.41302401 0.13420081 0.47073379]


Array indexing

In [70]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]      #shallow copy
print(b)
print(a[0,1])
b[0][0] = 77      #also modifying a
print(a[0,1])

[[2 3]
 [6 7]]
2
77


In [79]:
row_r1 = a[0, :]    # 일차원 -> 0번행의 모든열 출력
#밑에 두 array는 2차원 배열
row_r2 = a[1:2, 0:3]  # [a:b, c:d] -> a행부터 시작해서 (b-a)개 행 // c부터 시작해서 (d-c)개 열 출력
row_r3 = a[[1], :]  # a[1] 은 1행을 의미 -> a[[1], :]은 1행의 모든 열 출력
print(row_r1)
print(row_r2)
print(row_r3)

[ 1 77  3  4]
[[5 6 7]]
[[5 6 7 8]]


In [80]:
col_r1 = a[:, 1]    #int가 들어왔기 때문에 1차원
col_r2 = a[:, 1:2]  #1:2 slicing array가 들어왔기 때문에 2차원
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


In [91]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 1], [0, 0, 1]])    #a[[행리스트][열리스트]]
print(a)
print(a[[0,0], [1,1]])
print(np.array([a[0,1], a[0,1]]))

[1 3 4]
[[1 2]
 [3 4]
 [5 6]]
[2 2]
[2 2]


In [94]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])

print(a[np.arange(4), b])   #arange(4) -> [0, 1, 2, 3]

[ 1  6  7 11]


In [95]:
a[np.arange(4), b] += 10    #slicing은 shaloow copy이기 때문에 value 변경이 저장
print(a)          

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [97]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)      #ndarray return
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [98]:
print(a[bool_idx])    #a[boolean array] -> 조건문처럼 활용
print(a[a>2])         #조건문 -> array반환 -> 

[3 4 5 6]


#Array math

In [99]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [100]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [102]:
print(x * y)
print(y**x)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[   5.   36.]
 [ 343. 4096.]]
[[ 5. 12.]
 [21. 32.]]


In [103]:
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [107]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w.T))
print(np.dot(v, w))
print(v @ w)

219
219
219


In [108]:
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [110]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, 1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [111]:
print(x)
print("transpose\n", x.T)
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]
[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


Broadcasting

To work with arrays of different shapes when performing arithmetic operations.

In [114]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)
#루프를 도는게 느릴 수 있다

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [115]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                
y = x + vv  # Add x and vv elementwise
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [116]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [117]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [118]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [119]:
print(x.T)
print(w)
print((x.T + w).T)

[[1 4]
 [2 5]
 [3 6]]
[4 5]
[[ 5  6  7]
 [ 9 10 11]]


In [120]:
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]
